export const RPC_METHODS = {
  udbxOpen: "udbx.open",
  udbxClose: "udbx.close",
  udbxListDatasets: "udbx.listDatasets",
  udbxGetDatasetInfo: "udbx.getDatasetInfo",
  udbxExportDatabase: "udbx.exportDatabase",
  udbxImportDatabase: "udbx.importDatabase",
  udbxCreatePointDataset: "udbx.createPointDataset",
  udbxCreateLineDataset: "udbx.createLineDataset",
  udbxCreateRegionDataset: "udbx.createRegionDataset",
  udbxCreatePointZDataset: "udbx.createPointZDataset",
  udbxCreateLineZDataset: "udbx.createLineZDataset",
  udbxCreateRegionZDataset: "udbx.createRegionZDataset",
  udbxCreateTabularDataset: "udbx.createTabularDataset",
  udbxCreateCadDataset: "udbx.createCadDataset",
  datasetGetFields: "dataset.getFields",
  datasetGetById: "dataset.getById",
  datasetList: "dataset.list",
  datasetInsert: "dataset.insert",
  datasetInsertMany: "dataset.insertMany",
  datasetCount: "dataset.count",
  datasetUpdate: "dataset.update",
  datasetDelete: "dataset.delete"
} as const;
